Documentation:
- changed-files:
  - any-glob-to-any-file: 'docs/**'

Modules:
- changed-files:
  - any-glob-to-any-file: 'src/modules/**'

Github:
- changed-files:
  - any-glob-to-any-file: '.github/**'